version: '3.8'

services:
  app:
    build:
      args:
        user: thiel-serra
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/
    container_name: app_modularized
    volumes:
      - ./:/var/www
    restart: always
    networks:
      - network_stc1

  nginx:
    image: nginx:alpine
    container_name: app_modularized_nginx
    restart: always
    ports:
      - 8090:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - network_stc1    

  postgres:
    image: postgres:12.10-alpine
    container_name: "app_modularized_postgres"
    restart: always
    environment:
      POSTGRES_DB: transparencia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "./docker/postgres/data:/var/lib/postgresql/data"
    ports:
      - "5440:5432"
    networks:
      - network_stc1

networks:
  network_stc1:
    driver: bridge
